luci-app-ssr-plus: bump to 182-1
- Important improvement
Rewrite startup code to speed up startup
Same as global server, no need to start multiple processes
Use unified path and configuration

- Changes
Add Reset default settings
Optimize the use of shadowsocks plugin
Remove the sh script used in update and modify the UI usage
Remove Easylist China from adblock and add NEO DEV HOST
Adjust the parameters used by wget to ensure compatibility

- Fixes
Fix the issue of starting twice after apply in the server node list
Fix the problem that dnsmasq fails to start when the access control list contains wrong entries

diff --git a/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch b/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
--- a/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
+++ b/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
@@ -7,50 +7,22 @@
 # See /LICENSE for more information.
 #
 
+. $IPKG_INSTROOT/etc/init.d/shadowsocksr
 LOCK_FILE="/var/lock/ssr-switch.lock"
 [ -f "$LOCK_FILE" ] && exit 2
 touch "$LOCK_FILE"
+LOG_FILE=/var/log/ssrplus.log
+
 cycle_time=60
 switch_time=3
 normal_flag=0
 server_locate=0
 server_count=0
-NAME=shadowsocksr
 ENABLE_SERVER=nil
-CONFIG_SWTICH_FILE=/var/etc/${NAME}_t.json
-
 [ -n "$1" ] && cycle_time=$1
 [ -n "$2" ] && switch_time=$2
-
-uci_get_by_name() {
-	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
-	echo ${ret:=$3}
-}
-
-uci_get_by_type() {
-	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
-	echo ${ret:=$3}
-}
-
 DEFAULT_SERVER=$(uci_get_by_type global global_server)
 CURRENT_SERVER=$DEFAULT_SERVER
-
-#解析ip
-get_host_ip() {
-	local host=$1
-	local isip=""
-	local ip=$host
-	isip=$(echo $host | grep -E "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
-	if [ -z "$isip" ]; then
-		if [ "$host" != "${host#*:[0-9a-fA-F]}" ]; then
-			ip=$host
-		else
-			local ip=$(resolveip -4 -t 3 $host | awk 'NR==1{print}')
-			[ -z "$ip" ] && ip=$(wget -q -O- http://119.29.29.29/d?dn=$1 | awk -F ';' '{print $1}')
-		fi
-	fi
-	echo ${ip:="ERROR"}
-}
 
 #判断代理是否正常
 check_proxy() {
@@ -59,11 +31,11 @@ check_proxy() {
 	for i in $(seq 1 $try_count); do
 		/usr/bin/ssr-check www.google.com 80 $switch_time 1
 		if [ "$?" == "0" ]; then
-			# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Success, count=$i" >> /tmp/ssrplus.log
+			# echolog "Check Google Proxy Success, count=$i"
 			result=0
 			break
 		else
-			# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Fail, count=$i" >> /tmp/ssrplus.log
+			# echolog "Check Google Proxy Fail, count=$i"
 			/usr/bin/ssr-check www.baidu.com 80 $switch_time 1
 			if [ "$?" == "0" ]; then
 				result=1
@@ -77,19 +49,18 @@ check_proxy() {
 }
 
 test_proxy() {
-	local servername=$(get_host_ip $(uci_get_by_name $1 server))
+	local servername=$(uci_get_by_name $1 server)
 	local serverport=$(uci_get_by_name $1 server_port)
-	ipset add ss_spec_wan_ac $servername 2>/dev/null
-	ret1=$?
+	ipset add whitelist $servername 2>/dev/null
 	tcping -q -c 3 -i 1 -t 2 -p $serverport $servername
 	if [ "$?" -gt "0" ]; then
-		[ "$ret1" == "0" ] && ipset del ss_spec_wan_ac $servername 2>/dev/null
+		ipset del whitelist $servername 2>/dev/null
 		return 1
 	fi
 	/usr/bin/ssr-check $servername $serverport $switch_time
-	local ret2=$?
-	[ "$ret1" == "0" ] && ipset del ss_spec_wan_ac $servername 2>/dev/null
-	if [ "$ret2" == "0" ]; then
+	local ret=$?
+	ipset del whitelist $servername 2>/dev/null
+	if [ "$ret" == "0" ]; then
 		return 0
 	else
 		return 1
@@ -102,14 +73,13 @@ search_proxy() {
 	[ "$(uci_get_by_name $1 switch_enable 0)" != "1" ] && return 1
 	[ $ENABLE_SERVER != nil ] && return 0
 	[ "$1" == "$CURRENT_SERVER" ] && return 0
-	local servername=$(get_host_ip $(uci_get_by_name $1 server))
+	local servername=$(uci_get_by_name $1 server)
 	local serverport=$(uci_get_by_name $1 server_port)
-	ipset add ss_spec_wan_ac $servername 2>/dev/null
-	ret=$?
+	ipset add whitelist $servername 2>/dev/null
 	/usr/bin/ssr-check $servername $serverport $switch_time
-	local ret2=$?
-	[ "$ret" == "0" ] && ipset del ss_spec_wan_ac $servername 2>/dev/null
-	if [ "$ret2" == "0" ]; then
+	local ret=$?
+	ipset del whitelist $servername 2>/dev/null
+	if [ "$ret" == "0" ]; then
 		server_locate=$server_count
 		ENABLE_SERVER=$1
 		return 0
@@ -137,49 +107,49 @@ start() {
 	#不支持kcptun启用时的切换
 	[ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1" ] && return 1
 	while [ "1" == "1" ]; do #死循环
-		sleep $cycle_time
+		sleep 0000$cycle_time
 		LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
 		#判断当前代理是否为缺省服务器
 		if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ]; then
 			#echo "not default proxy"
-			echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >>/tmp/ssrplus.log
+			echolog "Current server is not default Main server, try to switch back."
 			#检查缺省服务器是否正常
 			if test_proxy $DEFAULT_SERVER; then
 				#echo "switch to default proxy"
-				echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >>/tmp/ssrplus.log
+				echolog "Main server is avilable."
 				#缺省服务器正常，切换回来
 				CURRENT_SERVER=$DEFAULT_SERVER
 				switch_proxy $CURRENT_SERVER
-				echo "$(date "+%Y-%m-%d %H:%M:%S") switch to default "$(uci_get_by_name $CURRENT_SERVER alias)" proxy!" >>/tmp/ssrplus.log
+				echolog "switch to default "$(uci_get_by_name $CURRENT_SERVER alias)" proxy!"
 			else
-				echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is NOT avilable.Continue using current server." >>/tmp/ssrplus.log
+				echolog "Main server is NOT avilable.Continue using current server."
 			fi
 		fi
 		#判断当前代理是否正常
-		#echo "$(date "+%Y-%m-%d %H:%M:%S") Start checking if the current server is available." >>/tmp/ssrplus.log
+		#echolog "Start checking if the current server is available."
 		check_proxy
 		current_ret=$?
 		if [ "$current_ret" == "1" ]; then
 			#当前代理错误，判断有无可用的服务器
 			#echo "current error"
-			echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >>/tmp/ssrplus.log
+			echolog "Current server error, try to switch another server."
 			select_proxy
 			if [ "$ENABLE_SERVER" != nil ]; then
 				#有其他服务器可用，进行切换
 				#echo $(uci_get_by_name $new_proxy server)
-				echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >>/tmp/ssrplus.log
+				echolog "Another server is avilable, now switching server."
 				CURRENT_SERVER=$ENABLE_SERVER
 				switch_proxy $CURRENT_SERVER
 				normal_flag=1
-				echo "$(date "+%Y-%m-%d %H:%M:%S") Switch to "$(uci_get_by_name $CURRENT_SERVER alias)" proxy!" >>/tmp/ssrplus.log
+				echolog "Switch to "$(uci_get_by_name $CURRENT_SERVER alias)" proxy!"
 			else
 				switch_proxy $CURRENT_SERVER
 				normal_flag=1
-				echo "$(date "+%Y-%m-%d %H:%M:%S") Try restart current server." >>/tmp/ssrplus.log
+				echolog "Try restart current server."
 			fi
 		else
 			normal_flag=0
-			# echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR No Problem." >>/tmp/ssrplus.log
+			# echolog "ShadowsocksR No Problem."
 		fi
 	done
 }
