luci-app-unblockneteasemusic: bump to v2.0

diff --git a/package/cnsztl/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic b/package/cnsztl/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
--- a/package/cnsztl/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
+++ b/package/cnsztl/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
@@ -11,13 +11,26 @@ enable="$(uci get unblockneteasemusic.@unblockneteasemusic[0].enabled)"
 http_port="$(uci get unblockneteasemusic.@unblockneteasemusic[0].http_port)"
 https_port="$(uci get unblockneteasemusic.@unblockneteasemusic[0].https_port)"
 type="$(uci get unblockneteasemusic.@unblockneteasemusic[0].musicapptype)"
-[ "$(uci get unblockneteasemusic.@unblockneteasemusic[0].enable_hijack)" -eq "1" ] && hijack_ways="$(uci get unblockneteasemusic.@unblockneteasemusic[0].hijack_ways)"
-
+hijack_ways="$(uci get unblockneteasemusic.@unblockneteasemusic[0].hijack_ways)"
 [ "$(uci get unblockneteasemusic.@unblockneteasemusic[0].pub_access)" -ne "0" ] && addr="0.0.0.0" || addr="${lan_addr}"
 [ "$(uci get unblockneteasemusic.@unblockneteasemusic[0].strict_mode)" -eq "1" ] && strict_mode="-s"
-[ "$(uci get unblockneteasemusic.@unblockneteasemusic[0].set_netease_server_ip)" -ne "0" ] && netease_server_ip="-f $(uci get unblockneteasemusic.@unblockneteasemusic[0].netease_server_ip)"
-[ "$(uci get unblockneteasemusic.@unblockneteasemusic[0].enable_proxy)" -ne "0" ] && proxy_server_ip="-u $(uci get unblockneteasemusic.@unblockneteasemusic[0].proxy_server_ip)"
 
+netease_server_ip="$(uci get unblockneteasemusic.@unblockneteasemusic[0].netease_server_ip)"
+[ -n "${netease_server_ip}" ] && netease_server_ip="-f ${netease_server_ip}"
+endpoint_url="$(uci get unblockneteasemusic.@unblockneteasemusic[0].endpoint_url)"
+[ -n "${endpoint_url}" ] && endpoint_url="-e ${endpoint_url}"
+proxy_server_ip="$(uci get unblockneteasemusic.@unblockneteasemusic[0].proxy_server_ip)"
+[ -n "${proxy_server_ip}" ] && proxy_server_ip="-u ${proxy_server_ip}"
+
+update_core(){
+	mkdir -p "/usr/share/unblockneteasemusic/core" >/dev/null 2>&1
+	rm -rf /usr/share/unblockneteasemusic/core/* >/dev/null 2>&1
+	curl -L "https://github.com/nondanee/UnblockNeteaseMusic/archive/master.tar.gz" -o "/usr/share/unblockneteasemusic/core/core.tar.gz" >/dev/null 2>&1
+	tar -zxf "/usr/share/unblockneteasemusic/core/core.tar.gz" -C "/usr/share/unblockneteasemusic/core/" >/dev/null 2>&1
+	mv /usr/share/unblockneteasemusic/core/UnblockNeteaseMusic-master/* "/usr/share/unblockneteasemusic/core/"
+	rm -rf "/usr/share/unblockneteasemusic/core/core.tar.gz /usr/share/unblockneteasemusic/core/UnblockNeteaseMusic-master" >/dev/null 2>&1
+	[ ! -e "/usr/share/unblockneteasemusic/core/app.js" ] && echo "Failed to download core." && exit 1
+}
 
 set_ipset(){
 	if [ "${set_type}" = "start" ]; then
@@ -32,14 +45,6 @@ set_ipset(){
 		cat > "/var/etc/unblockneteasemusic.include" <<-EOF
 if ! ipset list music >/dev/null; then ipset create music hash:ip; fi
 iptables -t nat -N cloud_music
-iptables -t nat -A cloud_music -d 0.0.0.0/8 -j RETURN
-iptables -t nat -A cloud_music -d 10.0.0.0/8 -j RETURN
-iptables -t nat -A cloud_music -d 127.0.0.0/8 -j RETURN
-iptables -t nat -A cloud_music -d 169.254.0.0/16 -j RETURN
-iptables -t nat -A cloud_music -d 172.16.0.0/12 -j RETURN
-iptables -t nat -A cloud_music -d 192.168.0.0/16 -j RETURN
-iptables -t nat -A cloud_music -d 224.0.0.0/4 -j RETURN
-iptables -t nat -A cloud_music -d 240.0.0.0/4 -j RETURN
 iptables -t nat -A cloud_music -p tcp --dport 80 -j REDIRECT --to-ports ${http_port}
 iptables -t nat -A cloud_music -p tcp --dport 443 -j REDIRECT --to-ports ${https_port}
 iptables -t nat -I PREROUTING -p tcp -m set --match-set music dst -j cloud_music
@@ -96,12 +101,14 @@ start()
 
 	[ "${enable}" -eq "0" ] && exit 0
 
+	update_core
+
 	if [ "${type}" = "default" ]; then
-		nohup node /usr/share/unblockneteasemusic/app.js -a ${addr} -p ${http_port}:${https_port} ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockneteasemusic.log 2>&1 &
+		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockneteasemusic.log 2>&1 &
 	elif [ "${type}" = "all" ]; then
-		nohup node /usr/share/unblockneteasemusic/app.js -a ${addr} -p ${http_port}:${https_port} -o kuwo migu xiami kugou qq joox netease ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockneteasemusic.log 2>&1 &
+		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" -o "kuwo migu qq xiami kugou joox" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockneteasemusic.log 2>&1 &
 	else
-		nohup node /usr/share/unblockneteasemusic/app.js -a ${addr} -p ${http_port}:${https_port} -o ${type} ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockneteasemusic.log 2>&1 &
+		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" -o "${type}" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockneteasemusic.log 2>&1 &
 	fi
 
 	if [ "*${hijack_ways}*" = "*use_ipset*" ]; then
