luci-app-unblockneteasemusic: improve core checking

diff --git a/package/ctcgfw/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic b/package/ctcgfw/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
--- a/package/ctcgfw/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
+++ b/package/ctcgfw/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
@@ -120,7 +120,8 @@ start()
 
 	[ "${enable}" -eq "0" ] && exit 0
 
-	[ ! -e "/usr/share/unblockneteasemusic/core/app.js" ] && rm -f /usr/share/unblockneteasemusic/local_ver && bash /usr/share/unblockneteasemusic/update_core.sh && [ $? -eq 1 ] && exit 1
+	[ ! -e "/usr/share/unblockneteasemusic/core/app.js" ] && rm -f /usr/share/unblockneteasemusic/local_ver && bash /usr/share/unblockneteasemusic/update_core.sh
+	[ ! -e "/usr/share/unblockneteasemusic/core/app.js" ] && echo "Core Not Found, please download it before starting." >>/tmp/unblockneteasemusic.log && exit 1
 
 	if [ "${type}" = "default" ]; then
 		nohup node /usr/share/unblockneteasemusic/core/app.js -a "${addr}" -p "${http_port}":"${https_port}" ${netease_server_ip} ${proxy_server_ip} ${endpoint_url} ${strict_mode} >>/tmp/unblockneteasemusic.log 2>&1 &
