Update G-DOCK.yml
Signed-off-by: Doanduy09 <96837081+Doanduy09@users.noreply.github.com>

diff --git a/.github/workflows/G-DOCK.yml b/.github/workflows/G-DOCK.yml
--- a/.github/workflows/G-DOCK.yml
+++ b/.github/workflows/G-DOCK.yml
@@ -1,4 +1,3 @@
-# Copyright (c) 2023
 name: G-DOCK
 
 on:
@@ -40,7 +39,7 @@ env:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
       - name: Checkout
@@ -51,20 +50,20 @@ jobs:
           DEBIAN_FRONTEND: noninteractive
         run: |
           sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-          sudo -E apt-get -qq update
-          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git \
-            libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex \
-            uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev \
-            texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf \
-            automake libtool autopoint ccache curl wget vim nano python2.7 python3 python3-pip \
-            python3-distutils python3-setuptools swig time xsltproc device-tree-compiler scons \
-            antlr3 gperf intltool mkisofs rsync ecj fastjar file g++ java-propose-classpath \
-            libncursesw5-dev haveged lrzsz
-          sudo -E apt-get -qq autoremove --purge
-          sudo -E apt-get -qq clean
+          sudo apt-get update -qq
+          sudo apt-get install -y curl
+          sudo -E apt-get -y install $(curl -fsSL git.io/depends-ubuntu-2004 | sed 's/lib32gcc1/lib32gcc-s1/')
+          sudo -E apt-get -y install build-essential cmake asciidoc binutils bzip2 gawk gettext git \
+            libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex \
+            uglifyjs git-core gcc-multilib g++-multilib p7zip-full msmtp libssl-dev texinfo libreadline-dev \
+            libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache \
+            curl wget vim nano python2 python3 python3-pip python3-ply haveged lrzsz device-tree-compiler \
+            scons antlr3 gperf intltool mkisofs rsync ecj fastjar file g++ libncursesw5-dev \
+            python3-distutils python3-setuptools swig time xsltproc
+          sudo apt-get -qq autoremove --purge
+          sudo apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
-          sudo mkdir -p /workdir
-          sudo chown $USER:$GROUPS /workdir
+          sudo mkdir -p /workdir && sudo chown $USER:$GROUPS /workdir
 
       - name: Clone source code
         working-directory: /workdir
@@ -107,6 +106,7 @@ jobs:
         if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
 
       - name: Download package
+        id: package
         run: |
           cd openwrt
           make defconfig
@@ -120,7 +120,7 @@ jobs:
           cd openwrt
           echo -e "$(nproc) thread compile"
           make -j $(($(nproc)+1)) || make -j4 || make -j4 V=s
-          echo "status=success"  >> $GITHUB_OUTPUT
+          echo "status=success" >> $GITHUB_OUTPUT
           grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
           [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
           echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
@@ -128,16 +128,16 @@ jobs:
       - name: If Error
         if: steps.compile.outcome == 'failure'
         run: |
-          cat openwrt/.config || true
+          cat openwrt/.config || echo "No config file found"
           echo '================================================================'
-          cd openwrt && make -j $(($(nproc)+1)) V=s || true
+          cd openwrt && make -j $(($(nproc)+1)) V=s
 
       - name: Check space usage
         if: (!cancelled())
         run: df -hT
 
       - name: Upload bin directory
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v3.1.2
         if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
         with:
           name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
@@ -154,12 +154,12 @@ jobs:
             echo "FIRMWARE=$PWD" >> $GITHUB_ENV
             echo "status=success" >> $GITHUB_OUTPUT
           else
-            echo "⚠️ Firmware output directory not found!"
+            echo "Firmware output directory not found!"
             exit 1
           fi
 
       - name: Upload firmware directory
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v3.1.2
         if: steps.organize.outputs.status == 'success' && !cancelled()
         with:
           name: DOANDUY-${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
@@ -170,8 +170,8 @@ jobs:
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         run: |
           touch release.txt
-          echo "release_tag=$(date +"%Y.%m.%d")"  >> $GITHUB_OUTPUT
-          echo "status=success"  >> $GITHUB_OUTPUT
+          echo "release_tag=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
+          echo "status=success" >> $GITHUB_OUTPUT
 
       - name: Upload firmware to release
         uses: softprops/action-gh-release@v2.0.8
